//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowGuardMonitoring.WebHost.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuthLocals {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthLocals() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FlowGuardMonitoring.WebHost.Resources.AuthLocals", typeof(AuthLocals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        internal static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        internal static string ConfirmPassLabel {
            get {
                return ResourceManager.GetString("ConfirmPassLabel", resourceCulture);
            }
        }
        
        internal static string ConfirmPassPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmPassPlaceholder", resourceCulture);
            }
        }
        
        internal static string EmailFieldRequiredErrorMsg {
            get {
                return ResourceManager.GetString("EmailFieldRequiredErrorMsg", resourceCulture);
            }
        }
        
        internal static string PasswordFieldRequiredErrorMsg {
            get {
                return ResourceManager.GetString("PasswordFieldRequiredErrorMsg", resourceCulture);
            }
        }
        
        internal static string PasswordsDontMatchErrorMsg {
            get {
                return ResourceManager.GetString("PasswordsDontMatchErrorMsg", resourceCulture);
            }
        }
        
        internal static string EmailFieldInvalidErrorMsg {
            get {
                return ResourceManager.GetString("EmailFieldInvalidErrorMsg", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordText {
            get {
                return ResourceManager.GetString("ForgotPasswordText", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordTitle", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordBtn {
            get {
                return ResourceManager.GetString("ForgotPasswordBtn", resourceCulture);
            }
        }
        
        internal static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        internal static string NewPasswordLabel {
            get {
                return ResourceManager.GetString("NewPasswordLabel", resourceCulture);
            }
        }
        
        internal static string NewPasswordPlaceholder {
            get {
                return ResourceManager.GetString("NewPasswordPlaceholder", resourceCulture);
            }
        }
        
        internal static string InvalidLoginErrorMsg {
            get {
                return ResourceManager.GetString("InvalidLoginErrorMsg", resourceCulture);
            }
        }
        
        internal static string UserLockedOutErrorMsg {
            get {
                return ResourceManager.GetString("UserLockedOutErrorMsg", resourceCulture);
            }
        }
        
        internal static string RegisterSuccessMessage {
            get {
                return ResourceManager.GetString("RegisterSuccessMessage", resourceCulture);
            }
        }
        
        internal static string PasswordTooShortErrorMsg {
            get {
                return ResourceManager.GetString("PasswordTooShortErrorMsg", resourceCulture);
            }
        }
        
        internal static string PasswordRequiresNonAlphanumericErrorMsg {
            get {
                return ResourceManager.GetString("PasswordRequiresNonAlphanumericErrorMsg", resourceCulture);
            }
        }
        
        internal static string PasswordRequiresLowerErrorMsg {
            get {
                return ResourceManager.GetString("PasswordRequiresLowerErrorMsg", resourceCulture);
            }
        }
        
        internal static string PasswordRequiresUpperErrorMsg {
            get {
                return ResourceManager.GetString("PasswordRequiresUpperErrorMsg", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordSuccessMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordSuccessMessage", resourceCulture);
            }
        }
        
        internal static string FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("FirstNamePlaceholder", resourceCulture);
            }
        }
        
        internal static string LastNameLabel {
            get {
                return ResourceManager.GetString("LastNameLabel", resourceCulture);
            }
        }
        
        internal static string LastNamePlaceholder {
            get {
                return ResourceManager.GetString("LastNamePlaceholder", resourceCulture);
            }
        }
        
        internal static string FirstNameLabel {
            get {
                return ResourceManager.GetString("FirstNameLabel", resourceCulture);
            }
        }
        
        internal static string FirstNameRequiredErrorMsg {
            get {
                return ResourceManager.GetString("FirstNameRequiredErrorMsg", resourceCulture);
            }
        }
        
        internal static string LastNameRequiredErrorMsg {
            get {
                return ResourceManager.GetString("LastNameRequiredErrorMsg", resourceCulture);
            }
        }
        
        internal static string ResetPasswordNewPasswordSameAsCurrent {
            get {
                return ResourceManager.GetString("ResetPasswordNewPasswordSameAsCurrent", resourceCulture);
            }
        }
    }
}
