//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowGuardMonitoring.WebHost.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuthLocals {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthLocals() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FlowGuardMonitoring.WebHost.Resources.AuthLocals", typeof(AuthLocals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        internal static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        internal static string ConfirmPassLabel {
            get {
                return ResourceManager.GetString("ConfirmPassLabel", resourceCulture);
            }
        }
        
        internal static string ConfirmPassPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmPassPlaceholder", resourceCulture);
            }
        }
        
        internal static string EmailFieldRequiredErrorMsg {
            get {
                return ResourceManager.GetString("EmailFieldRequiredErrorMsg", resourceCulture);
            }
        }
        
        internal static string PasswordFieldRequiredErrorMsg {
            get {
                return ResourceManager.GetString("PasswordFieldRequiredErrorMsg", resourceCulture);
            }
        }
        
        internal static string PasswordsDontMatchErrorMsg {
            get {
                return ResourceManager.GetString("PasswordsDontMatchErrorMsg", resourceCulture);
            }
        }
        
        internal static string EmailFieldInvalidErrorMsg {
            get {
                return ResourceManager.GetString("EmailFieldInvalidErrorMsg", resourceCulture);
            }
        }
    }
}
